### ISSUE TITLE
It killed my internet and how to fix it

### ISSUE THREAD

**Issue by GLaDOS-418** [simeononsecurity/System-Wide-Windows-Ad-Blocker#1]
* downloaded `soswindowsadblocker.ps1`
* unblocked it via properties in windows right click option menu
* ran the script.
* The expectation was to block just ads but, no requests are being resolved.

**Desktop:**
 - OS: Windows 11 Home 21H2
 - Browser : firefox 100, chrome 101

are there any prerequisites? any step before/after the script installation? 

how to fix/revert these changes?

**Comment by simeononsecurity** [comment]
There are no prerequisites or post-requisites. 
However, if you're having issues you can use the following guide to learn how to edit your hosts file and clear out the changes that were made by the script. https://www.liquidweb.com/kb/edit-host-file-windows-10/

**Comment by simeononsecurity** [comment]
We just tested it again on a test machine and we're not experiencing the same results. 
You can try running it again as the script will replace the changes.
Additionally, it is a rather large host file, you might be having issues keeping it in memory.
Try rebooting following running the script again.

**Comment by simeononsecurity** [comment]
@GLaDOS-418 
Any updates?

**Comment by GLaDOS-418** [comment]
> @GLaDOS-418 
> Any updates?

could not figure out the root cause and ended up reverting the changes. i booted into the windows safe mode and removed everything so that no host is now blocked and I'm back to square one with ads. I'll probably try it again sometime later.

**Comment by simeononsecurity** [comment]
> > @GLaDOS-418
> > Any updates?
> 
> could not figure out the root cause and ended up reverting the changes. i booted into the windows safe mode and removed everything so that no host is now blocked and I'm back to square one with ads. I'll probably try it again sometime later.

@GLaDOS-418 

Hate to hear it didn't work out for you. The script is dynamic and pulls from 3rd party resources. It is possible that it bugged out when you tried to pull said resources.
Feel free to try it again in the future. 

 We wish we could recreate what issues you were having. It works on all of our test systems and we haven't seen what you're talking about just yet.
Glad you were able to reverse it successfully however.

**Comment by reneas** [comment]
So i had the same issue and apparently it's caused by the `hosts` file being too big and therefore crashing windows' `dnscache`.
As stated [here](https://serverfault.com/a/336525) you can just deactivate the dns service since "It sounds bizarre, but the DNS client isn't needed to do DNS". 
[Here](https://www.thewindowsclub.com/enable-the-dns-client-service-if-greyed-out) is a guide on how to stop the service but I couldn't do that wihlie running the system. What I did was to boot into safemode, renamed the `hosts` file and then deactivated the auto-start of the service via the `regedit` method stated in the link.
After reboot I named the file back to it's original name and so far everything is working fine!
Thanks for making this script my friend and bye bye in-app-advertisement!
